import LegalLayout from "../components/LegalLayout";

export default function Terms() {
  return (
    <LegalLayout eyebrow="Legal" title="Terms of Use" updated="August 2026">
      <h2>Agreement to terms</h2>
      <p>
        These Terms of Use govern your access to and use of the iBellori website and any
        early-access dashboard products we make available (together, the "Services"). By
        using the Services, you agree to these terms. If you don't agree, please don't use
        the Services.
      </p>

      <h2>Who we are</h2>
      <p>
        iBellori builds business intelligence and dashboard tools that help business owners
        understand information already spread across spreadsheets, e-commerce platforms, and
        other business systems.
      </p>

      <h2>Using iBellori</h2>
      <p>
        You may use the Services only for lawful purposes and in accordance with these terms.
        If you connect a third-party account (such as Etsy or Pinterest) to an iBellori
        product, you're responsible for making sure you have the right to authorize that
        connection, and for complying with that platform's own terms of service.
      </p>

      <h2>Early-stage products</h2>
      <p>
        iBellori is under active development. Features may change, be added, or be removed
        without notice, and some products described on this site may not yet be publicly
        available. We'll do our best to communicate meaningful changes to anyone using an
        active iBellori product.
      </p>

      <h2>Intellectual property</h2>
      <p>
        The iBellori name, logo, and website content are owned by iBellori unless otherwise
        noted. You may not copy, modify, or redistribute our branding or website content
        without permission.
      </p>

      <h2>Third-party platforms</h2>
      <p>
        iBellori products may connect to third-party platforms such as Etsy and Pinterest.
        We are not responsible for those platforms' availability, accuracy, or their own
        terms and policies. Your use of any connected platform remains subject to that
        platform's own terms.
      </p>

      <h2>Disclaimer</h2>
      <p>
        The Services are provided "as is," without warranties of any kind, express or
        implied. We do not guarantee that dashboards or reports generated by iBellori will be
        complete, accurate, or uninterrupted, and any business decisions you make based on
        information from iBellori remain your own responsibility.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, iBellori will not be liable for any indirect,
        incidental, or consequential damages arising from your use of the Services.
      </p>

      <h2>Changes to these terms</h2>
      <p>
        We may update these terms as iBellori's products evolve. We'll update the date at the
        top of this page whenever changes are made.
      </p>

      <h2>Contact us</h2>
      <p>
        Questions about these terms can be sent to{" "}
        <a href="mailto:hello@ibellori.com">hello@ibellori.com</a>.
      </p>
    </LegalLayout>
  );
}
